### ISSUE TITLE
Shared Recipe

### ISSUE THREAD

**Issue by VortexWinds** [Commander-Mawile/Mawcraft#1]
Shared recipe issue: When you put stone into a regular furnace to craft stone tiles as instructed by the recipe in the NEI/JEI you get circuit plates instead of stone tiles. There is only one alternative to craft these which is using a crystal furnace from chromaticraft to craft this. This essential issue is the circuit plates and stone tiles share the exact same recipe and it defaults to circuit plates meaning you only receive circuit plates as I have tested.

**Comment by Commander-Mawile** [comment]
Issue has been fixed in Mawcraft v1.2. BluePower and ProjectRed wafers now share the same oredict.
